### PR TITLE
wgpu 0.6, third time's the charm

### PR DESCRIPTION
**Pull request by kazimuth**
This is a PR building on @alekspickle's work in #655. All major issues fixed, I had to make some fairly large changes to cope w/ wgpu adding an alignment requirement on buffers used in texture-buffer copies.

Remaining work:
- [x] new API bikeshedding
- [x] address remaining TODOs
- [x] get wgpu texture sequence example working (currently crashing with OOM for some reason)
- [x] add tests for a variety of image sizes on new alignment logic (how should I write tests that use GPU?)

### CODE REVIEW

**Comment by kazimuth** [comment]
Alright, fixed the last broken example. (The problem was gfx-rs/wgpu#1006, luckily it was just a bad diagnostic message for a mistake on my end, which I was able to fix.)

@mitchmindtree, now waiting on review. I *think* everything works -- I'd like to write more tests to be sure, but I'm not sure how to write tests that use the GPU.

**Comment by mitchmindtree** [comment]
Hi @kazimuth, awesome work!

Just wanted to let you know that I started writing up a review, but I think it might be easier to do a PR against your branch. I should have one up soon.

**Comment by mitchmindtree** [comment]
Okydoke, I've started opening up some PRs [here](https://github.com/kazimuth/nannou/pulls).

I've just noticed the `wgpu_teapot_camera` example appears to be panicking when starting it up:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os(OsError { line: 1246, file: "/home/mindtree/.cargo/registry/src/git
hub.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/window.rs", error: XMisc("Cursor could not be grabbed: grab location not vie
wable") })', examples/wgpu/wgpu_teapot_camera/wgpu_teapot_camera.rs:95:5
```
Looks like something might have changed in the way cursor grabbing works in a recent winit update - my suspicion is that this might be due to the cursor not being over the window when a grab attempt was made. Might be worth trying to update to winit 0.23 to see if it resolves this. If not, addressing this some other way should be easy enough.

I've also noticed that all examples appear to crash when attempting to resize with the following error:

```
thread 'main' panicked at 'failed to acquire next swapchain texture: Outdated', /home/mindtree/programming/rust/nannou/nannou/src/app.rs:1108:
45
```

I've yet to dig into this, though it looks like it might just be an unhandled error?

Going to move onto some other work for tonight, but will check in again here soon!

**Comment by kazimuth** [comment]
Merged your PRs! (History here is getting pretty tangled -- do you think we should rebase onto master?)

Good catch on the example resizing -- I'm running a tiling window manager so I didn't notice it :) I'm a little busier this week but should be able to look at some of the other issues by the weekend.

**Comment by kazimuth** [comment]
...this fell out of my inbox, whoops. I think we can actually finish this up this week.

**Comment by mitchmindtree** [comment]
Awesome, looking forward to it @kazimuth :)

**Comment by kazimuth** [comment]
...Okay I actually got to this now lol.

I merged master -- no conflicts! -- and updated wgpu, and now the resizing bug doesn't happen anymore! :tada: I love when things work out like that.

So, I think this is ready to merge. Let me know if you want any final changes or any git history rewriting... I'll be honest though, we're pretty tangled here, might be a bit beyond my git-fu.

**Comment by kazimuth** [comment]
...Hm, that error is surprising. Looks unrelated to my changes, a library breakage. The dependency chain goes `examples` -> `audrey 0.2` -> `sample 0.9.1`. Maybe a rust update broke the old `sample` library? The latest version on crates is `0.11.0`.

**Comment by mitchmindtree** [comment]
Awesome!

> The dependency chain goes examples -> audrey 0.2 -> sample 0.9.1. Maybe a rust update broke the old sample library? The latest version on crates is 0.11.0.

That version of `sample` is certainly quite old - the crate itself has since been deprecated in favour of the `dasp` crates, or specifically in this case `dasp_sample`. I think `audrey` could use some love.

Alternatively, we could just switch to using `hound` instead of `audrey` seeing as we only need to load a `wav` in this particular example. If we do that, we should probably rename the example to make its clear that its just `wav` example, not audio files in general (which is the idea behind `audrey`).

Btw, did we ever get to the bottom of that resizing bug?

**Comment by kazimuth** [comment]
Yeah, I'll update that example to use `wav` for now.

Re, resizing, I think it was related to the bug discussed here: https://github.com/gfx-rs/wgpu-rs/pull/434

I'm not sure what fixed it but it doesn't seem to be caused by any wgpu changes. Downgrading from 0.6.2 to 0.6.0 doesn't make the bug show up again.

**Comment by kazimuth** [comment]
Update: actually, looks like somebody already made a PR to fix `audrey`'s `sample` dep: https://github.com/RustAudio/audrey/pull/28

@mitchmindtree, if you merge that over there and make a release I could also use that in this PR :)

**Comment by mitchmindtree** [comment]
> Update: actually, looks like somebody already made a PR to fix audrey's sample dep: RustAudio/audrey#28

Ahh good spot!

> @mitchmindtree, if you merge that over there and make a release I could also use that in this PR :)

Just published `audrey` `0.3.0` :)

**Comment by mitchmindtree** [comment]
> Re, resizing, I think it was related to the bug discussed here: gfx-rs/wgpu-rs#434

I just pulled `wgpu-0.6-3`, ran `cargo update` and tried the examples again. Curiously, `simple_ui.rs` does not seem to `panic!` during resize, but the `draw.rs` example does still panic with:

```thread 'main' panicked at 'failed to acquire next swapchain texture: Outdated', /home/mindtree/programming/rust/nannou/nannou/src/app.rs:1110:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::expect
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:933
   4: nannou::app::run_loop::{{closure}}
             at ./nannou/src/app.rs:1108
   5: winit::platform_impl::platform::sticky_exit_callback
             at /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
   6: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:312
   7: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390
   8: winit::platform_impl::platform::EventLoop<T>::run
             at /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645
   9: winit::event_loop::EventLoop<T>::run
             at /home/mindtree/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  10: nannou::app::run_loop
             at ./nannou/src/app.rs:1059
  11: nannou::app::Builder<M,E>::run
             at ./nannou/src/app.rs:491
  12: nannou::app::SketchBuilder<E>::run
             at ./nannou/src/app.rs:516
  13: draw::main
             at ./examples/draw/draw.rs:4
  14: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
```
I'm yet to dig deeper and try the other examples.

**Comment by kazimuth** [comment]
oh, hm, I just realized the crashes are only happening sporadically unless i resize to a certain aspect ratio, which is why i didn't spot it. Okay then, that's definitely an issue with the swapchain not being rebuilt on resize.

...except that nannou [does rebuild the swapchain on resize](https://github.com/nannou-org/nannou/blob/787c2cafe1f46c024461af1d1e223b4c6e66acfe/nannou/src/app.rs#L1217-L1234). Hm. Maybe it's a race condition or something?

**Comment by kazimuth** [comment]
Okay, I've done some debugging and... it really does look like winit's just not delivering the resize event in time. Like, if you inspect the winit `Window` state at the time of the `Outdated` error getting thrown, as far as winit/x11 is concerned the window hasn't changed size. Frankly i have no idea which component in our towering stack of graphics abstractions is causing this -- I can't get it to happen w/ the `wgpu` + `winit` examples by themselves, but it seems to be racy, so those might just not be as heavy as nannou. It *could* be something to do with our event loop structure too, but I really don't know what it would be.

I implemented a simple workaround for now. In the event loop, we now check if the swapchain is `Outdated` when we get a redraw request, and if so, don't actually do the redraw. Then we'll keep spinning the event loop until the resize event actually shows up, at which point we can resize the swapchain and go on our merry way. This does sometimes cause the Vulkan validation layers to complain; I check them by adding `pretty_env_logger` to the examples and using `RUST_LOG=debug`. Occasionally they warn that a framebuffer is being destroyed before a command buffer has been destroyed... that doesn't sound good, and I don't know exactly what's causing it. But the app does keep running. (Famous last words...)

**Comment by kazimuth** [comment]
Also, side note, the `simple_audio_file` example is now crashing with an error from ALSA on my machine. I'd appreciate if somebody else could double-check that, because my laptop's audio is haunted and I don't trust it.

**Comment by nebkor** [comment]
I checkout out your branch, and I'm not getting the crashes on resize due to the outdated swapchain anymore, but I am getting a crash during texture allocation because it runs out of memory if I resize enough (on the `simple_ui` demo and `simple_audio_file`).

```
thread 'main' panicked at 'not enough memory left', /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
stack backtrace:
   0:     0x55a00827f940 - std::backtrace_rs::backtrace::libunwind::trace::h04d12fdcddff82aa
                               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
[snip panic/backtrace-related traces]
  15:     0x55a007b61b35 - <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}::h7ea4235f0a2d0abf
                               at /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:35
  16:     0x55a007c9ad5c - core::result::Result<T,E>::unwrap_or_else::h98ed67637ead169c
                               at /home/ardent/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:825:23
  17:     0x55a007cb81c9 - <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::h3f2de8b71eb5f606
                               at /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:1355:9
  18:     0x55a007b5f0f0 - <wgpu::backend::direct::Context as wgpu::Context>::device_create_texture::hc001687a281fb16e
                               at /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/backend/direct.rs:831:9
  19:     0x55a007b63c2a - wgpu::Device::create_texture::hc33a5b1ab3b4c045
                               at /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.2/src/lib.rs:1507:17
  20:     0x55a007578d18 - nannou::wgpu::texture::Builder::build::had333152a45200cd
                               at /home/ardent/git/nannou/nannou/src/wgpu/texture/mod.rs:524:31
  21:     0x55a0075be2c2 - nannou::frame::create_lin_srgba_msaa_texture::hff8a17e995f9cd72
                               at /home/ardent/git/nannou/nannou/src/frame/mod.rs:330:5
  22:     0x55a0075be41d - nannou::frame::create_intermediary_lin_srgba::h82bb0ce597d0c434
                               at /home/ardent/git/nannou/nannou/src/frame/mod.rs:354:27
  23:     0x55a0075be06d - nannou::frame::RenderData::new::hcc5dade843549160
                               at /home/ardent/git/nannou/nannou/src/frame/mod.rs:297:13
  24:     0x55a0075d270b - nannou::window::Window::rebuild_swap_chain::h07ddeabda459c617
                               at /home/ardent/git/nannou/nannou/src/window.rs:1366:31
  25:     0x55a00746425c - nannou::app::run_loop::{{closure}}::h7da2f3ced8bfc232
                               at /home/ardent/git/nannou/nannou/src/app.rs:1248:25
 26:     0x55a007466f09 - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}::{{closure}}::hd782faf7615cda5b
                               at /home/ardent/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:425:29
  27:     0x55a00741e394 - winit::platform_impl::platform::sticky_exit_callback::heda4e5ca68ec1a4a
....
```

For what it's worth, `simple_audio_file` works for me; here's the overall view of my alsa setup:
```
!!Kernel Information
!!------------------

Kernel release:    5.8.0-41-generic
Operating System:  GNU/Linux
Architecture:      x86_64
Processor:         x86_64
SMP Enabled:       Yes


!!ALSA Version
!!------------

Driver version:     k5.8.0-41-generic
Library version:    1.2.3.2
Utilities version:  1.2.3


!!Loaded ALSA modules
!!-------------------

snd_hda_intel
snd_hda_intel


!!Sound Servers on this system
!!----------------------------

Pulseaudio:
      Installed - Yes (/usr/bin/pulseaudio)
      Running - Yes


!!Soundcards recognised by ALSA
!!-----------------------------

 0 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xfcba0000 irq 84
 1 [Generic        ]: HDA-Intel - HD-Audio Generic
                      HD-Audio Generic at 0xfca00000 irq 86


!!PCI Soundcards installed in the system
!!--------------------------------------

0b:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 HDMI Audio [1002:ab38]
        Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 HDMI Audio [1002:ab38]
0d:00.4 Audio device [0403]: Advanced Micro Devices, Inc. [AMD] Starship/Matisse HD Audio Controller [1022:1487]
        Subsystem: ASUSTeK Computer Inc. Starship/Matisse HD Audio Controller [1043:8797]
```

**Comment by mitchmindtree** [comment]
@kazimuth 

> Okay, I've done some debugging and... it really does look like winit's just not delivering the resize event in time.

Thanks so much for the legendary effort diving into this! I'm more than happy to merge this as is. I think simply not drawing on the `Outdated` event is fine until we can work out a better solution.

Sorry again for the wait, I think it's about time we landed this :)

---

@nebkor 

> but I am getting a crash during texture allocation because it runs out of memory if I resize enough (on the simple_ui demo and simple_audio_file).

I think this might be an older issue: https://github.com/nannou-org/nannou/issues/491

**Comment by kazimuth** [comment]
Heck yeah! Happy to have contributed to nannou, it's a cool project :)

**Pull request merged**
