### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by oherrala**
Two commits:

 *  Update cgmath 0.17 and remove approx crate
     cgmath crate publishes three traits from approx 0.3 crate (`AbsDiff`, `RelativeEq`, `UlpsEq`) which are also implemented in this commit while removing the old ApproxEq implementation from approx 0.1 crate.
 * Update everything else. No code changes required here.

### CODE REVIEW

**Comment by oherrala** [comment]
Apparently `cgmath` and `approx` parts are also changed in #434, but that PR also seems to change many other things.

**Comment by mitchmindtree** [comment]
Thanks for this @oherrala!

I think there's one line of formatting that travis is unhappy about - would you mind running `cargo fmt`?

**Comment by oherrala** [comment]
@mitchmindtree Sorry about that, cargo fmt done.

**Comment by tpltnt** [comment]
looks good to me.

**Pull request merged**
