### PR TITLE
Make nannou package compile in WASM environment

### PR DESCRIPTION
**Pull request by Woyten**
Hi. This is a minimal example showing which changes will allow to compile the nannou module against the `wasm32-unknown-unknown` target.

Disclaimer: I am not saying that:
- Nannou Apps will run in a Browser after these changes. There are still some things to do.
- This PR should be merged. But it could! :wink:

This PR relates to #475.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Nice to see a start on this!

One thing that might be worth adding while landing wasm support would be one new [CI job](https://github.com/nannou-org/nannou/blob/master/.github/workflows/nannou.yml) that tries to build one or more of the examples for the wasm target, or something along these lines. Normally I would say CI testing of specific platforms is best left for the cross platform crates like winit and cpal. However in our case I think it might be easy for us to accidentally break wasm compatibility otherwise, particularly as some library APIs just aren't compatible with wasm (like those wgpu items you had to gate in this PR) and it's not always obvious what those are.

**Comment by Woyten** [comment]
Sorry I haven't responded yet. I will rebase this PR and see how to adapt the CI job once #737 is merged.

**Comment by Woyten** [comment]
@mitchmindtree I upgraded this PR to the newest Nannou version and added a CI check.

**Comment by Woyten** [comment]
@mitchmindtree Currently, it's not possible to compile the whole Nannou tree to WASM. `nannou_timeline` depends on `envelope` which depends on `num` which depends on `rustc-serialize`. `rustc-serialize` will not receive WASM support (https://github.com/rust-lang-deprecated/rustc-serialize/pull/190#issuecomment-378057459). This means, a new `envelope` version without the implicit `rustc-serialize` dependency is needed.

**Comment by Woyten** [comment]
Other problematic libraries that need to be removed or hidden behind a feature switch are `socket2` and `home`.

**Comment by Woyten** [comment]
@mitchmindtree The PR has been updated to the newest Nannou release. I propose to merge the PR s.t. the main `nannou` package doesn't lose WASM compatibility in the future.

**Pull request closed without merging**
