### PR TITLE
Rename window build methods

### LINKED ISSUE #451: Rename window builder methods from `with_*` to `*`
It seems a little needlessly verbose for each of the builder methods to begin with `with_`. It is clear that each of these methods are specifying some properties of the window being built either way. It would be nice to rename the builder methods to remove `with_`.

E.g.:

- `with_title` -> `title`
- `with_fullscreen` -> `fullscreen`
- `with_dimensions` -> `dimensions`

etc.

### PR DESCRIPTION
**Pull request by anchnk**
Tracking progress of the methods that should be renamed from window Builder pattern:

- [x] `with_dimensions`
- [x] `with_min_dimensions`
- [x] `with_max_dimensions`
- [x] `with_title`
- [x] `with_fullscreen`
- [x] `with_maximized`
- [x] `with_visibility`
- [x] `with_transparency`
- [x] `with_decorations`
- [x] `with_multitouch`

Close #451

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Thanks a lot @anchnk! I'll take a look and merge this soon, before I go any further on #452.

**Comment by anchnk** [comment]
Awesome @mitchmindtree! Should we log issues for the missing examples/tests on some building methods?

**Comment by mitchmindtree** [comment]
Opening issues for missing examples is a great idea!

W.r.t. tests - I'm not sure how to best go about CI-compatible testing for some of these APIs where they call-down into very platform-specific functionality like window-building, graphics calls etc. I think it's very difficult to come up with something that is both easy to maintain and provides test results that are useful and worth the maintenance cost. That said if you have some ideas on this feel free to open issues!

**Comment by anchnk** [comment]
I am not sure how to test that either TBH. Having examples that covers these method would already be a big enhancement to ensure things are still working if something changes at some point. 

It might sound silly but does a testing strategy such as screenshot diffing could be considered? Such as what's done by Jest in the browser domain for instance. Some kind of headless window where one could access relevant context properties could be another option but as you said it would cost a lot of extra time for very small benefits.

**Comment by mitchmindtree** [comment]
Yeah it would be handy if `wgpu` had a software rendering backend that made it easier to setup automated testing. I think I opened an issue up at the `gfx-rs` repo a while back about implementing a software implementation, but I don't think it's a trivial job and I'm not sure there's been any action on it.

Anyways, this looks good to me!

**Pull request merged**
